/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Sprint Hub API
 * The sprint hub API description
 * OpenAPI spec version: 1.0
 */
import { customInstance } from '../lib/orval';
export interface RegisterDto {
  /** The username of the user */
  username: string;
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
}

export interface LoginDto {
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
}

export type CreateUserDtoRole = typeof CreateUserDtoRole[keyof typeof CreateUserDtoRole];


export const CreateUserDtoRole = {
  USER: 'USER',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export interface CreateUserDto {
  email: string;
  password: string;
  role: CreateUserDtoRole;
  name: string;
  avatarUrl: string;
}

export type UpdateUserDtoRole = typeof UpdateUserDtoRole[keyof typeof UpdateUserDtoRole];


export const UpdateUserDtoRole = {
  USER: 'USER',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export interface UpdateUserDto {
  email: string;
  role: UpdateUserDtoRole;
  name: string;
  avatarUrl: string;
}

export type AuditlogControllerFindAllParams = {
page?: number;
limit?: number;
/**
 * Search keyword or email
 */
search?: string;
sortBy?: string;
order?: AuditlogControllerFindAllOrder;
action?: AuditlogControllerFindAllAction;
entity?: string;
entityId?: string;
actorId?: string;
};

export type AuditlogControllerFindAllOrder = typeof AuditlogControllerFindAllOrder[keyof typeof AuditlogControllerFindAllOrder];


export const AuditlogControllerFindAllOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AuditlogControllerFindAllAction = typeof AuditlogControllerFindAllAction[keyof typeof AuditlogControllerFindAllAction];


export const AuditlogControllerFindAllAction = {
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
} as const;

export type UsersControllerFindAllParams = {
page?: number;
limit?: number;
/**
 * Search keyword or email
 */
search?: string;
sortBy?: string;
order?: UsersControllerFindAllOrder;
role?: UsersControllerFindAllRole;
status?: UsersControllerFindAllStatus;
};

export type UsersControllerFindAllOrder = typeof UsersControllerFindAllOrder[keyof typeof UsersControllerFindAllOrder];


export const UsersControllerFindAllOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type UsersControllerFindAllRole = typeof UsersControllerFindAllRole[keyof typeof UsersControllerFindAllRole];


export const UsersControllerFindAllRole = {
  USER: 'USER',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export type UsersControllerFindAllStatus = typeof UsersControllerFindAllStatus[keyof typeof UsersControllerFindAllStatus];


export const UsersControllerFindAllStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BANNED: 'BANNED',
} as const;

export const getSprintHubAPI = () => {
const appControllerGetHello = (

 ) => {
      return customInstance<void>(
      {url: `/`, method: 'GET'
    },
      );
    }

const authControllerRegister = (
    registerDto: RegisterDto,
 ) => {
      return customInstance<void>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto
    },
      );
    }

const authControllerLogin = (
    loginDto: LoginDto,
 ) => {
      return customInstance<void>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto
    },
      );
    }

const authControllerRefresh = (

 ) => {
      return customInstance<void>(
      {url: `/auth/refresh`, method: 'POST'
    },
      );
    }

const authControllerLogout = (

 ) => {
      return customInstance<void>(
      {url: `/auth/logout`, method: 'POST'
    },
      );
    }

const auditlogControllerFindAll = (
    params?: AuditlogControllerFindAllParams,
 ) => {
      return customInstance<void>(
      {url: `/audit-logs`, method: 'GET',
        params
    },
      );
    }

const auditlogControllerFindOne = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/audit-logs/${id}`, method: 'GET'
    },
      );
    }

const usersControllerMe = (

 ) => {
      return customInstance<void>(
      {url: `/users/me`, method: 'GET'
    },
      );
    }

const usersControllerCreate = (
    createUserDto: CreateUserDto,
 ) => {
      return customInstance<void>(
      {url: `/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserDto
    },
      );
    }

const usersControllerFindAll = (
    params?: UsersControllerFindAllParams,
 ) => {
      return customInstance<void>(
      {url: `/users`, method: 'GET',
        params
    },
      );
    }

const usersControllerFindOne = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/users/${id}`, method: 'GET'
    },
      );
    }

const usersControllerUpdate = (
    id: string,
    updateUserDto: UpdateUserDto,
 ) => {
      return customInstance<void>(
      {url: `/users/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto
    },
      );
    }

const usersControllerRemove = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/users/${id}`, method: 'DELETE'
    },
      );
    }

return {appControllerGetHello,authControllerRegister,authControllerLogin,authControllerRefresh,authControllerLogout,auditlogControllerFindAll,auditlogControllerFindOne,usersControllerMe,usersControllerCreate,usersControllerFindAll,usersControllerFindOne,usersControllerUpdate,usersControllerRemove}};
export type AppControllerGetHelloResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['appControllerGetHello']>>>
export type AuthControllerRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['authControllerRegister']>>>
export type AuthControllerLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['authControllerLogin']>>>
export type AuthControllerRefreshResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['authControllerRefresh']>>>
export type AuthControllerLogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['authControllerLogout']>>>
export type AuditlogControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['auditlogControllerFindAll']>>>
export type AuditlogControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['auditlogControllerFindOne']>>>
export type UsersControllerMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['usersControllerMe']>>>
export type UsersControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['usersControllerCreate']>>>
export type UsersControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['usersControllerFindAll']>>>
export type UsersControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['usersControllerFindOne']>>>
export type UsersControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['usersControllerUpdate']>>>
export type UsersControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSprintHubAPI>['usersControllerRemove']>>>
