/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedTasksRouteImport } from './routes/_protected/tasks'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedRoleRouteImport } from './routes/_protected/role'
import { Route as ProtectedReportRouteImport } from './routes/_protected/report'
import { Route as ProtectedKanbanRouteImport } from './routes/_protected/kanban'
import { Route as ProtectedHelpRouteImport } from './routes/_protected/help'
import { Route as ProtectedCalendarRouteImport } from './routes/_protected/calendar'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as ProtectedUserIndexRouteImport } from './routes/_protected/user/index'
import { Route as ProtectedUserIdRouteImport } from './routes/_protected/user/$id'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTasksRoute = ProtectedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRoleRoute = ProtectedRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedReportRoute = ProtectedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedKanbanRoute = ProtectedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHelpRoute = ProtectedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCalendarRoute = ProtectedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const ProtectedUserIndexRoute = ProtectedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUserIdRoute = ProtectedUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof GuestLoginRoute
  '/calendar': typeof ProtectedCalendarRoute
  '/help': typeof ProtectedHelpRoute
  '/kanban': typeof ProtectedKanbanRoute
  '/report': typeof ProtectedReportRoute
  '/role': typeof ProtectedRoleRoute
  '/settings': typeof ProtectedSettingsRoute
  '/tasks': typeof ProtectedTasksRoute
  '/user/$id': typeof ProtectedUserIdRoute
  '/user/': typeof ProtectedUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/login': typeof GuestLoginRoute
  '/calendar': typeof ProtectedCalendarRoute
  '/help': typeof ProtectedHelpRoute
  '/kanban': typeof ProtectedKanbanRoute
  '/report': typeof ProtectedReportRoute
  '/role': typeof ProtectedRoleRoute
  '/settings': typeof ProtectedSettingsRoute
  '/tasks': typeof ProtectedTasksRoute
  '/user/$id': typeof ProtectedUserIdRoute
  '/user': typeof ProtectedUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_protected/calendar': typeof ProtectedCalendarRoute
  '/_protected/help': typeof ProtectedHelpRoute
  '/_protected/kanban': typeof ProtectedKanbanRoute
  '/_protected/report': typeof ProtectedReportRoute
  '/_protected/role': typeof ProtectedRoleRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/tasks': typeof ProtectedTasksRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/user/$id': typeof ProtectedUserIdRoute
  '/_protected/user/': typeof ProtectedUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/help'
    | '/kanban'
    | '/report'
    | '/role'
    | '/settings'
    | '/tasks'
    | '/user/$id'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calendar'
    | '/help'
    | '/kanban'
    | '/report'
    | '/role'
    | '/settings'
    | '/tasks'
    | '/user/$id'
    | '/user'
  id:
    | '__root__'
    | '/_guest'
    | '/_protected'
    | '/_guest/login'
    | '/_protected/calendar'
    | '/_protected/help'
    | '/_protected/kanban'
    | '/_protected/report'
    | '/_protected/role'
    | '/_protected/settings'
    | '/_protected/tasks'
    | '/_protected/'
    | '/_protected/user/$id'
    | '/_protected/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/tasks': {
      id: '/_protected/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ProtectedTasksRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/role': {
      id: '/_protected/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof ProtectedRoleRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/report': {
      id: '/_protected/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ProtectedReportRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/kanban': {
      id: '/_protected/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof ProtectedKanbanRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/help': {
      id: '/_protected/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ProtectedHelpRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/calendar': {
      id: '/_protected/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof ProtectedCalendarRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_protected/user/': {
      id: '/_protected/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof ProtectedUserIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/user/$id': {
      id: '/_protected/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof ProtectedUserIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedCalendarRoute: typeof ProtectedCalendarRoute
  ProtectedHelpRoute: typeof ProtectedHelpRoute
  ProtectedKanbanRoute: typeof ProtectedKanbanRoute
  ProtectedReportRoute: typeof ProtectedReportRoute
  ProtectedRoleRoute: typeof ProtectedRoleRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTasksRoute: typeof ProtectedTasksRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedUserIdRoute: typeof ProtectedUserIdRoute
  ProtectedUserIndexRoute: typeof ProtectedUserIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCalendarRoute: ProtectedCalendarRoute,
  ProtectedHelpRoute: ProtectedHelpRoute,
  ProtectedKanbanRoute: ProtectedKanbanRoute,
  ProtectedReportRoute: ProtectedReportRoute,
  ProtectedRoleRoute: ProtectedRoleRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTasksRoute: ProtectedTasksRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedUserIdRoute: ProtectedUserIdRoute,
  ProtectedUserIndexRoute: ProtectedUserIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
