/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as protectedIndexRouteImport } from './routes/(protected)/index'
import { Route as protectedTasksRouteImport } from './routes/(protected)/tasks'
import { Route as protectedRoleRouteImport } from './routes/(protected)/role'
import { Route as protectedReportRouteImport } from './routes/(protected)/report'
import { Route as protectedKanbanRouteImport } from './routes/(protected)/kanban'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as protectedCalendarRouteImport } from './routes/(protected)/calendar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedTasksRoute = protectedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedRoleRoute = protectedRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedReportRoute = protectedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedKanbanRoute = protectedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedCalendarRoute = protectedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/calendar': typeof protectedCalendarRoute
  '/dashboard': typeof protectedDashboardRoute
  '/kanban': typeof protectedKanbanRoute
  '/report': typeof protectedReportRoute
  '/role': typeof protectedRoleRoute
  '/tasks': typeof protectedTasksRoute
  '/': typeof protectedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof protectedCalendarRoute
  '/dashboard': typeof protectedDashboardRoute
  '/kanban': typeof protectedKanbanRoute
  '/report': typeof protectedReportRoute
  '/role': typeof protectedRoleRoute
  '/tasks': typeof protectedTasksRoute
  '/': typeof protectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(protected)/calendar': typeof protectedCalendarRoute
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(protected)/kanban': typeof protectedKanbanRoute
  '/(protected)/report': typeof protectedReportRoute
  '/(protected)/role': typeof protectedRoleRoute
  '/(protected)/tasks': typeof protectedTasksRoute
  '/(protected)/': typeof protectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/kanban'
    | '/report'
    | '/role'
    | '/tasks'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/kanban'
    | '/report'
    | '/role'
    | '/tasks'
    | '/'
  id:
    | '__root__'
    | '/(protected)'
    | '/login'
    | '/(protected)/calendar'
    | '/(protected)/dashboard'
    | '/(protected)/kanban'
    | '/(protected)/report'
    | '/(protected)/role'
    | '/(protected)/tasks'
    | '/(protected)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/tasks': {
      id: '/(protected)/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof protectedTasksRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/role': {
      id: '/(protected)/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof protectedRoleRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/report': {
      id: '/(protected)/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof protectedReportRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/kanban': {
      id: '/(protected)/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof protectedKanbanRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/calendar': {
      id: '/(protected)/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof protectedCalendarRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedCalendarRoute: typeof protectedCalendarRoute
  protectedDashboardRoute: typeof protectedDashboardRoute
  protectedKanbanRoute: typeof protectedKanbanRoute
  protectedReportRoute: typeof protectedReportRoute
  protectedRoleRoute: typeof protectedRoleRoute
  protectedTasksRoute: typeof protectedTasksRoute
  protectedIndexRoute: typeof protectedIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedCalendarRoute: protectedCalendarRoute,
  protectedDashboardRoute: protectedDashboardRoute,
  protectedKanbanRoute: protectedKanbanRoute,
  protectedReportRoute: protectedReportRoute,
  protectedRoleRoute: protectedRoleRoute,
  protectedTasksRoute: protectedTasksRoute,
  protectedIndexRoute: protectedIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
