/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as protectedTasksRouteImport } from './routes/(protected)/tasks'
import { Route as protectedSettingsRouteImport } from './routes/(protected)/settings'
import { Route as protectedRoleRouteImport } from './routes/(protected)/role'
import { Route as protectedReportRouteImport } from './routes/(protected)/report'
import { Route as protectedKanbanRouteImport } from './routes/(protected)/kanban'
import { Route as protectedHelpRouteImport } from './routes/(protected)/help'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as protectedCalendarRouteImport } from './routes/(protected)/calendar'
import { Route as protectedUserIndexRouteImport } from './routes/(protected)/user/index'
import { Route as protectedUserIdRouteImport } from './routes/(protected)/user/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedTasksRoute = protectedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsRoute = protectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedRoleRoute = protectedRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedReportRoute = protectedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedKanbanRoute = protectedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedHelpRoute = protectedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedCalendarRoute = protectedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUserIndexRoute = protectedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUserIdRoute = protectedUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/calendar': typeof protectedCalendarRoute
  '/dashboard': typeof protectedDashboardRoute
  '/help': typeof protectedHelpRoute
  '/kanban': typeof protectedKanbanRoute
  '/report': typeof protectedReportRoute
  '/role': typeof protectedRoleRoute
  '/settings': typeof protectedSettingsRoute
  '/tasks': typeof protectedTasksRoute
  '/user/$id': typeof protectedUserIdRoute
  '/user/': typeof protectedUserIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof protectedCalendarRoute
  '/dashboard': typeof protectedDashboardRoute
  '/help': typeof protectedHelpRoute
  '/kanban': typeof protectedKanbanRoute
  '/report': typeof protectedReportRoute
  '/role': typeof protectedRoleRoute
  '/settings': typeof protectedSettingsRoute
  '/tasks': typeof protectedTasksRoute
  '/user/$id': typeof protectedUserIdRoute
  '/user': typeof protectedUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(protected)/calendar': typeof protectedCalendarRoute
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(protected)/help': typeof protectedHelpRoute
  '/(protected)/kanban': typeof protectedKanbanRoute
  '/(protected)/report': typeof protectedReportRoute
  '/(protected)/role': typeof protectedRoleRoute
  '/(protected)/settings': typeof protectedSettingsRoute
  '/(protected)/tasks': typeof protectedTasksRoute
  '/(protected)/user/$id': typeof protectedUserIdRoute
  '/(protected)/user/': typeof protectedUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/help'
    | '/kanban'
    | '/report'
    | '/role'
    | '/settings'
    | '/tasks'
    | '/user/$id'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/help'
    | '/kanban'
    | '/report'
    | '/role'
    | '/settings'
    | '/tasks'
    | '/user/$id'
    | '/user'
  id:
    | '__root__'
    | '/(protected)'
    | '/login'
    | '/(protected)/calendar'
    | '/(protected)/dashboard'
    | '/(protected)/help'
    | '/(protected)/kanban'
    | '/(protected)/report'
    | '/(protected)/role'
    | '/(protected)/settings'
    | '/(protected)/tasks'
    | '/(protected)/user/$id'
    | '/(protected)/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/tasks': {
      id: '/(protected)/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof protectedTasksRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/role': {
      id: '/(protected)/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof protectedRoleRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/report': {
      id: '/(protected)/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof protectedReportRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/kanban': {
      id: '/(protected)/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof protectedKanbanRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/help': {
      id: '/(protected)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof protectedHelpRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/calendar': {
      id: '/(protected)/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof protectedCalendarRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/user/': {
      id: '/(protected)/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof protectedUserIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/user/$id': {
      id: '/(protected)/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof protectedUserIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedCalendarRoute: typeof protectedCalendarRoute
  protectedDashboardRoute: typeof protectedDashboardRoute
  protectedHelpRoute: typeof protectedHelpRoute
  protectedKanbanRoute: typeof protectedKanbanRoute
  protectedReportRoute: typeof protectedReportRoute
  protectedRoleRoute: typeof protectedRoleRoute
  protectedSettingsRoute: typeof protectedSettingsRoute
  protectedTasksRoute: typeof protectedTasksRoute
  protectedUserIdRoute: typeof protectedUserIdRoute
  protectedUserIndexRoute: typeof protectedUserIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedCalendarRoute: protectedCalendarRoute,
  protectedDashboardRoute: protectedDashboardRoute,
  protectedHelpRoute: protectedHelpRoute,
  protectedKanbanRoute: protectedKanbanRoute,
  protectedReportRoute: protectedReportRoute,
  protectedRoleRoute: protectedRoleRoute,
  protectedSettingsRoute: protectedSettingsRoute,
  protectedTasksRoute: protectedTasksRoute,
  protectedUserIdRoute: protectedUserIdRoute,
  protectedUserIndexRoute: protectedUserIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
